### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by kielerboy** [DerEnderman/CyberStateRP#6]
hello how i can translate the build.js on the client html folder . i the see text so \u0422\u0435\u043A\u0441\u0442 \u043F\u0440\u0435\u0432\u044B\u0448\u0430\u0435\u0442 \u0434\u043B\u0438\u043D\u0443 540 \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432

here is the image https://prnt.sc/u7u68z

**Comment by DerEnderman** [comment]
You can change this here -> https://github.com/DerEnderman/CyberStateRP/tree/master/AppReact/src

You need recompile the files.

Also check : https://github.com/DerEnderman/CyberStateRP/blob/master/AppReact/package.json

**Comment by MagedSamir** [comment]
Any updates with translation ? are you planning on pushing the commits soon?

**Comment by DerEnderman** [comment]
Since i get banned for no reason from AltV. No!
